# -*- coding: utf-8 -*-
"""Modelo_Prediccion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r1H-bJFMX5imRj42UbPlg-4mrAV1Qzae
"""

#Vincula Colab con Drive (monta el Drive en la máquina virtual que nos provee Google)
from google.colab import drive

drive.mount('/content/DRIVE')

"""#LIBRERIAS"""

#Importo librerias
import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn import tree
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

"""#OBTENCIÓN DEL DATA SET"""

#Lee el csv y lo convierte a un df de pandas
path = '/content/DRIVE/MyDrive/2 - CDIA/CDIA/PPT2/train.csv'
dataset_crudo = pd.read_csv(path)
dataset_crudo

"""#**MODELO: ARBOL DE DESICIÓN (DT)**"""

#Predecimos con los datos del TEST
random_forest_prediction = random_forest.predict(Datos_test_normalizado)
decision_tree_prediction = decision_tree.predict(Datos_test_normalizado)